export default data = {
  cars: [
    {
      id: 1,
      model: "Audi A3 Sport",
      img: require("./assets/Audi_A3_Sport_30_TFSi_Saloon.jpg"),
      automatic: true,
      electric: true,
      category: 2,
      seats: 5,
    },

    {
      id: 2,
      model: "Audi A4 B9",
      img: require("./assets/Audi_A4_B9_sedans.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 3,
      model: "Audi Q5 e-tron",
      img: require("./assets/Audi_Q5_e-tron_001.jpg"),
      automatic: true,
      electric: true,
      category: 3,
      seats: 5,
    },
    {
      id: 4,
      model: "ABMW 318d SE",
      img: require("./assets/BMW_318d_SE_Automatic.jpg"),
      automatic: true,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 5,
      model: "BMW 420i Sport",
      img: require("./assets/BMW_420i_Sport_Automatic.jpg"),
      automatic: true,
      electric: false,
      category: 2,
      seats: 4,
    },
    {
      id: 6,
      model: "BMW F40",
      img: require("./assets/BMW_F40.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 7,
      model: "BMW iX",
      img: require("./assets/BMW_iX.jpg"),
      automatic: true,
      electric: true,
      category: 3,
      seats: 5,
    },

    {
      id: 8,
      model: "BMW M235i xDrive",
      img: require("./assets/BMW_M235i_xDrive_Gran_Coupe.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 9,
      model: "Toyota Allion",
      img: require("./assets/FAW_Toyota_Allion.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 10,
      model: "Mercedes AMG GT 63",
      img: require("./assets/Mercedes-AMG_GT_63.jpg"),
      automatic: true,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 11,
      model: "Mercedes-Benz A 180 Progressive",
      img: require("./assets/Mercedes-Benz_A_180_Progressive.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 12,
      model: "Mercedes-Benz C257",
      img: require("./assets/Mercedes-Benz_C257.jpg"),
      automatic: true,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 13,
      model: "Mercedes-Benz W247",
      img: require("./assets/Mercedes-Benz_W247.jpg"),
      automatic: true,
      electric: true,
      category: 2,
      seats: 5,
    },

    {
      id: 14,
      model: "Peugeot 508 GT",
      img: require("./assets/Peugeot_508_GT.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 15,
      model: "PRenault Kaptur 9900",
      img: require("./assets/Renault_Kaptur_9900.jpg"),
      automatic: true,
      electric: true,
      category: 3,
      seats: 5,
    },

    {
      id: 16,
      model: "Renault Megane E-Tech",
      img: require("./assets/Renault_Megane_E-Tech.jpg"),
      automatic: true,
      electric: true,
      category: 23,
      seats: 5,
    },

    {
      id: 17,
      model: "Renault Megane Sedan Intens",
      img: require("./assets/Renault_Megane_Intens_sedan.jpg"),
      automatic: true,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 18,
      model: "Toyota Corolla Altis E210",
      img: require("./assets/Toyota_Corolla_Altis__E210.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },

    {
      id: 19,
      model: "Toyota GR Yaris XP21",
      img: require("./assets/Toyota_GR_Yaris_XP21.jpg"),
      automatic: false,
      electric: false,
      category: 1,
      seats: 5,
    },

    {
      id: 20,
      model: "Volkswagen Arteon Shooting Brake",
      img: require("./assets/Volkswagen_Arteon_Shooting_Brake.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 21,
      model: "Volkswagen Gran Santana",
      img: require("./assets/Volkswagen_Gran_Santana.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 22,
      model: "Volkswagen ID.3",
      img: require("./assets/Volkswagen_ID.3_1st_Front.jpg"),
      automatic: true,
      electric: true,
      category: 2,
      seats: 5,
    },
    {
      id: 23,
      model: "Volkswagen Passat GTE facelift",
      img: require("./assets/Volkswagen_Passat_GTE_facelift_1.4.jpg"),
      automatic: false,
      electric: false,
      category: 2,
      seats: 5,
    },
    {
      id: 24,
      model: "Volkswagen Polo 1.2 TSI ",
      img: require("./assets/Volkswagen_Polo_1.2_TSI.jpg"),
      automatic: false,
      electric: false,
      category: 1,
      seats: 5,
    },
  ],
};
